seed_everything: 1
trainer:
  accelerator: auto
  precision: 32
  devices: 2
  logger: lightning.pytorch.loggers.WandbLogger
  gradient_clip_val: 0.5
  max_epochs: 500
  accumulate_grad_batches: 16
  log_every_n_steps: 5
  check_val_every_n_epoch: 2
  callbacks:
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args: 
        logging_interval: step
    - class_path: lightning.pytorch.callbacks.early_stopping.EarlyStopping
      init_args:
        monitor: loss_val
        patience: 5
        mode: min
model:
  stepwise: true
  max_num_steps: 20
  lr: 0.0001
  warmup_steps: 500
  model_name: t5-large
  num_beams: 10
  topk: 10
  verifier_ckpt: null
  verifier_weight: 0.0
  proof_search: false
  oracle_prover: false
  oracle_verifier: false
data:
  dataset: entailmentbank
  sample_goal: hypothesis # hypothesis | intermediates
  subtree_proved_prob: 0.5
  subtree_proved_all_or_none: true
  batch_size: 16
  num_workers: 4
  max_input_len: 1024
  max_output_len: 64
  path_train: ../data/entailment_trees_emnlp2021_data_v3/dataset/task_1/train.jsonl
  path_val: ../data/entailment_trees_emnlp2021_data_v3/dataset/task_1/dev.jsonl
  path_test: ../data/entailment_trees_emnlp2021_data_v3/dataset/task_1/test.jsonl
