seed_everything: 1
trainer:
  accelerator: gpu
  default_root_dir: ./output/entailmentbank_verifier_task2_default
  precision: 32
  devices: 2
  num_nodes: 1
  plugins: null
  max_epochs: 50
  callbacks:
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: step
    - class_path: lightning.pytorch.callbacks.early_stopping.EarlyStopping
      init_args:
        monitor: loss_val
        patience: 5
        mode: min
model:
  lr: 1e-5
  warmup_steps: 2500
  model_name: roberta-large
  pos_weight: 128.0
data:
  dataset: entailmentbank
  batch_size: 128
  num_workers: 8
  max_num_premises: 4
  max_input_len: 256
  irrelevant_distractors_only: true
  path_train: ../data/entailment_trees_emnlp2021_data_v3/dataset/task_2/train.jsonl
  path_val: ../data/entailment_trees_emnlp2021_data_v3/dataset/task_2/dev.jsonl